name: wishlist

services:
  api:
    image: ghcr.io/egor1025/wishlist:latest
    container_name: wishlist-api

    ports:
      - "7000:6000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./db:/api/db
