name: wishlist

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: wishlist-image
    container_name: wishlist-api

    ports:
      - "7000:6000"

    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

    volumes:
      - ../db:/api/db
